services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server