[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
futures-util = "0.3.31"
log = "0.4.27"
tokio = {version = "1.44.2", features = ["macros", "rt-multi-thread", "sync"]}
tokio-tungstenite = "0.26.2"
